# subreddit_mapper.py
"""
Utility functions for mapping subreddit names to countries.
"""

import pycountry
import re
from rapidfuzz import fuzz

# A constant dictionary mapping native country names, demonyms,
# and language names to standardized English names.
# Kept at the module level as it's a fixed resource.
_NATIVE_NAMES_MAP = {
    # Europe
    'deutschland': 'Germany',
    'français': 'France',
    'españa': 'Spain',
    'italia': 'Italy',
    'portugal': 'Portugal',
    'ellada': 'Greece', 'Ελλάδα': 'Greece',
    'polska': 'Poland',
    'nederland': 'Netherlands',
    'belgië': 'Belgium', 'belgique': 'Belgium',
    'suomi': 'Finland',
    'sverige': 'Sweden',
    'norge': 'Norway',
    'danmark': 'Denmark',
    'íslensku': 'Iceland',
    'österreich': 'Austria',
    'schweiz': 'Switzerland', 'suisse': 'Switzerland', 'svizzera': 'Switzerland',
    'česko': 'Czechia',
    'magyarország': 'Hungary',
    'românia': 'Romania',
    'hrvatska': 'Croatia',
    'srbija': 'Serbia',
    'rossiya': 'Russia', 'Россия': 'Russia',
    'ukrayina': 'Ukraine', 'Україна': 'Ukraine',
    'lietuva': 'Lithuania',
    'latvija': 'Latvia',
    'eesti': 'Estonia',

    # Asia
    'nippon': 'Japan', 'nihon': 'Japan', '日本': 'Japan',
    'zhongguo': 'China', '中国': 'China',
    'hanguk': 'South Korea', '한국': 'South Korea',
    'bharat': 'India', 'भारत': 'India',
    'pakistan': 'Pakistan',
    'bangladesh': 'Bangladesh',
    'türkiye': 'Turkey',
    'iran': 'Iran',
    'al-arabiyyah as-saudiyyah': 'Saudi Arabia',
    'misr': 'Egypt',

    # Americas
    'brasil': 'Brazil',
    'méxico': 'Mexico',
    'argentina': 'Argentina',
    'colombia': 'Colombia',
    'perú': 'Peru',
    'chile': 'Chile',
    'venezuela': 'Venezuela',

    # Common demonyms / language names
    'svenska': 'Sweden',
    'dansk': 'Denmark',
    'norsk': 'Norway',
    'finnish': 'Finland',
    'dutch': 'Netherlands',
    'polish': 'Poland',
    'german': 'Germany',
    'french': 'France',
    'spanish': 'Spain',
    'italian': 'Italy',
    'portuguese': 'Portugal',
    'turkish': 'Turkey',
    'greek': 'Greece',
    'russian': 'Russia',
    'japanese': 'Japan'
}


def create_country_map():
    """
    Builds a comprehensive map of country name variations to standardized English names.
    
    Combines names from pycountry (official and common) with a custom
    map of native names, demonyms, and language names.
    
    Returns:
        dict: A dictionary mapping various names (lowercase) to a standard country name.
    """
    country_map = {}
    
    # 1. Build from pycountry
    for country in pycountry.countries:
        names = [country.name.lower()]
        if hasattr(country, "official_name"):
            names.append(country.official_name.lower())
        
        # Avoid short codes for now (they cause false positives)
        for n in names:
            country_map[n] = country.name
            
    # 2. Add custom native/language names
    country_map.update(_NATIVE_NAMES_MAP)
    
    return country_map


def find_country(subreddit, country_map):
    """
    Attempts to find a single matching country for a given subreddit name.
    
    Args:
        subreddit (str): The name of the subreddit (e.g., "r/norway" or "norway").
        country_map (dict): The map generated by create_country_map().
        
    Returns:
        str or None: The standardized country name if a match is found, else None.
    """
    name = subreddit.lower().replace("r/", "")
    # Split on anything not a lowercase letter
    tokens = re.split(r'[^a-z]+', name)
    joined = ''.join(tokens)

    # Direct token match
    for token in tokens + [joined]:
        if token in country_map:
            return country_map[token]
    
    # Starts/ends with full country names (e.g. norwaynews)
    for key in country_map:
        cleaned_key = key.replace(' ', '')
        if len(cleaned_key) < 4:  # ignore short codes
            continue
        if name.startswith(cleaned_key) or name.endswith(cleaned_key):
            return country_map[key]
    
    # Fuzzy match (high threshold, long names only)
    if len(name) > 6:
        best_match, best_score = None, 0
        for key, country in country_map.items():
            if len(key) < 4:  # skip short country codes
                continue
            score = fuzz.partial_ratio(key, name)
            if score > 90 and score > best_score:
                best_match, best_score = country, score
        
        if best_match:
            return best_match
    
    return None


def map_subreddits_to_countries(subreddit_list, country_map):
    """
    Iterates over a list of subreddit names and maps them to countries.
    
    Args:
        subreddit_list (iterable): A list or pandas Series of subreddit names.
        country_map (dict): The map generated by create_country_map().
        
    Returns:
        dict: A dictionary mapping {subreddit_name: country_name} for all found matches.
    """
    matches = {}
    for s in subreddit_list:
        country = find_country(s, country_map)
        if country:
            matches[s] = country
    return matches